apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: webapp-backend
  namespace: webapp
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - webapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
