namespace: webapp

frontend:
  image:
    repository: webapp-frontend
    tag: latest
  replicas: 2
  port: 80

backend:
  image:
    repository: webapp-backend
    tag: latest
  replicas: 2
  port: 8080

config:
  appMessage: "Hello from ConfigMap"

secret:
  appSecretToken: "super-secret-token"

ingress:
  className: nginx
  host: apps.local

serviceAccount:
  name: webapp-sa
